name: Tests

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  lint:
    name: Lint and Analyse
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, xml, hash, ctype, iconv, curl
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-stable"

      - name: Validate composer.lock
        run: composer validate --strict

      - name: Run lint and static analysis
        run: composer lint

  test:
    name: Test P${{ matrix.php }} - L${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: [11, 12, 13]
        exclude:
          - php: 8.2
            laravel: 13
        include:
          - laravel: 11
            testbench: 9.*
          - laravel: 12
            testbench: 10.*
          - laravel: 13
            testbench: 11.*

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, hash, ctype, iconv, curl
          coverage: none

      - name: Configure Composer for older Laravel versions
        if: matrix.laravel == 8 || matrix.laravel == 9
        run: composer config audit.block-insecure false

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
